[package]
name = "rs-hp4x"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
terminal_size = "0.4.0"
thiserror = "1.0.65"
winnow = { version = "0.6.20", features = [] }
